version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    networks:
      - queue-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    networks:
      - queue-net

  redis:
    image: redis:7.2
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    networks:
      - queue-net

  app:
    image: yourorg/virtual-queue:latest # Replace with your built image
    depends_on:
      - kafka
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prd
    restart: always
    networks:
      - queue-net
    ports:
      - "8080:8080"

networks:
  queue-net:
    driver: bridge
